name: Canary Multi-Turn

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:

  canary-multi-turn:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        model:
          - mistralai/mistral-7b-instruct-v0.3           # $0.07
    steps:
      - uses: actions/checkout@v4
      - run: ./gamal.js tests/canary-multi-turn.txt
        env:
          LLM_API_BASE_URL: ${{ secrets.LLM_API_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}
