name: Canary Multi-Turn

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:

  canary-multi-turn:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: ./gamal.js tests/en/canary-multi-turn.txt
        env:
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
