name: General Knowledge

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:

  general-knowledge:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: ./gamal.js tests/en/general-knowledge.txt
        env:
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          BRAVE_SEARCH_API_KEY: ${{ secrets.BRAVE_SEARCH_API_KEY }}
