name: General Knowledge

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:

  general-knowledge:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Run SearXNG
        uses: ./.github/actions/searxng
        timeout-minutes: 3
      - run: ./gamal.js tests/en/general-knowledge.txt
        env:
          SEARXNG_URL: http://localhost:9000
          LLM_API_BASE_URL: ${{ secrets.LLM_API_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ secrets.LLM_CHAT_MODEL }}
