name: German tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:

  canary-multi-turn:
    runs-on: ubuntu-22.04
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v4
      - run: ./gamal.js tests/de/canary-multi-turn.txt
        env:
          LLM_API_BASE_URL: ${{ secrets.LLM_API_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ secrets.LLM_CHAT_MODEL }}

  high-school-stem:
    runs-on: ubuntu-22.04
    needs: canary-multi-turn
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: ./gamal.js tests/de/high-school-stem.txt
        env:
          LLM_API_BASE_URL: ${{ secrets.LLM_API_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ secrets.LLM_CHAT_MODEL }}
