name: High-school STEM

on: [workflow_dispatch, push, pull_request]

jobs:

  high-school-stem:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        model:
          - mistralai/mistral-7b-instruct-v0.3           # $0.07 [32K]
          - meta-llama/llama-3-8b-instruct               # $0.07 [ 8K]
          - openchat/openchat-8b                         # $0.08 [ 8K]
          - microsoft/phi-3-medium-4k-instruct           # $0.14 [ 4K]
          - nousresearch/hermes-2-pro-llama-3-8b         # $0.15 [ 8K]
          - google/gemma-2-9b-it                         # $0.20 [ 8K]
          - mistralai/mixtral-8x7b-instruct              # $0.24 [32K]
          - meta-llama/llama-3-70b-instruct              # $0.59 [ 8K]
          - qwen/qwen-2-72b-instruct                     # $0.59/$0.79 [  32K]
    steps:
      - uses: actions/checkout@v4

      - run: ./query-llm.js tests/high-school-stem.txt
        env:
          LLM_API_BASE_URL: ${{ secrets.LLM_API_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}
