name: High-school STEM

on: [workflow_dispatch, push, pull_request]

jobs:

  high-school-stem:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        model:
          - mistralai/mistral-7b-instruct-v0.3           # $0.07 [32K]
          - meta-llama/llama-3-8b-instruct               # $0.07 [ 8K]
          - openchat/openchat-7b                         # $0.07 [ 8K]
          - openchat/openchat-8b                         # $0.08 [ 8K]
          - qwen/qwen-4b-chat                            # $0.09 [32K]
          - microsoft/phi-3-medium-4k-instruct           # $0.14 [ 4K]
          - nousresearch/hermes-2-pro-llama-3-8b         # $0.15 [ 8K]
          - teknium/openhermes-2.5-mistral-7b            # $0.17 [ 4K]
          - nousresearch/nous-hermes-2-mistral-7b-dpo    # $0.18 [32K]
          - open-orca/mistral-7b-openorca                # $0.18 [ 8K]
          - mistralai/mixtral-8x7b-instruct              # $0.24 [32K]
          - qwen/qwen-14b-chat                           # $0.27 [32K]
          - meta-llama/llama-3-70b-instruct              # $0.59 [ 8K]
          - mistralai/mixtral-8x22b-instruct             # $0.65 [64K]
    steps:
      - uses: actions/checkout@v4

      - run: ./query-llm.js tests/high-school-stem.txt
        env:
          LLM_API_BASE_URL: ${{ secrets.LLM_API_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_CHAT_MODEL: ${{ matrix.model }}
