name: Test on Together

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - run: ./gamal.js tests/en/canary-multi-turn.txt
        env:
          LLM_API_BASE_URL: 'https://api.together.xyz/v1'
          LLM_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          LLM_CHAT_MODEL: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo'
