name: Test with Small LLM

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Run SearXNG
        uses: ./.github/actions/searxng
        timeout-minutes: 3
      - name: Prepare LLM
        uses: ./.github/actions/prepare-llm
        timeout-minutes: 7
      - run: ./gamal.js tests/en/canary-multi-turn.txt
        env:
          SEARXNG_URL: http://localhost:9000
          LLM_API_BASE_URL: http://127.0.0.1:8080/v1
          LLM_CHAT_MODEL: 'qwen2.5-1.5b'
          LLM_JSON_SCHEMA: 1
