name: Test on OpenAI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Run SearXNG
        uses: ./.github/actions/searxng
        timeout-minutes: 3
      - run: ./gamal.js tests/en/canary-multi-turn.txt
        if: ${{ env.LLM_API_KEY != '' }}
        env:
          SEARXNG_URL: http://localhost:9000
          LLM_API_BASE_URL: 'https://api.openai.com/v1'
          LLM_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLM_CHAT_MODEL: 'gpt-4o-mini'
          LLM_JSON_SCHEMA: 1
