name: Test on Lepton

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - run: ./gamal.js tests/en/canary-multi-turn.txt
        env:
          LLM_API_BASE_URL: 'https://llama3-1-8b.lepton.run/api/v1'
          LLM_API_KEY: ${{ secrets.LEPTON_API_KEY }}
          LLM_CHAT_MODEL: 'llama3-1-8b'
